
/**** BATCH REQUEST PER SEC SINCE THE LAST SERVER RESTART    ********/
SELECT 
	OBJECT_NAME "PERFORMANCE CATEGORY",
	COUNTER_NAME "COUNTER",
	CAST (CAST(CNTR_VALUE AS DECIMAL(18,3)) / CAST(DATEDIFF(SS, ( SELECT CREATE_DATE FROM
                            SYS.DATABASES
                            WHERE NAME LIKE 'TEMPDB'),GETDATE()) AS DECIMAL(18,3)) AS DECIMAL(18,3))
                            AS AVG_BATCHES_PER_SEC
FROM	SYS.DM_OS_PERFORMANCE_COUNTERS 
WHERE	
--COUNTER_NAME LIKE 'BATCH REQUESTS/SEC%'   
1=1
 

