USE [master]
ALTER DATABASE [SOADB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [SOADB] FROM  
DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\SOADB_20180508.bak' WITH  FILE = 1,  
MOVE N'SOADB' TO N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SOADB.mdf',  
MOVE N'SOADB_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SOADB_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [SOADB] SET MULTI_USER

GO


